version: '3.8'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - web-db

  web-db:
    container_name: web-postgres
    image: postgres:latest
    env_file: ./web-config/web.env
    ports:
      - '5432:5432'
    volumes:
      - /${HOME}/data/postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always

  web-pgadmin:
    container_name: web-pgadmin4
    image: dpage/pgadmin4
    env_file: ./web-config/web.env
    ports:
      - '8080:80'
    depends_on:
      - web-db
    restart: always

networks:
  postgres:
    driver: bridge